default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: 'localhost'

development:
  <<: *default
  database: route2_development

test:
  <<: *default
  database: route2_test

production:
  <<: *default
  database: route2_production
  username: route2_production
  password: <%= ENV['PRODUCTION_DB_PASSWORD'] %>
